config/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/index.html'), name="home"),
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('mail/', include('mail.urls')),
    path('message/', include('message.urls')),
    path('sns/', include('sns.urls')),
    path('upload_form/', include('upload_form.urls')),
    path('graph/', include('graph.urls')),
]

django_app/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
]

graph/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views
 
app_name = 'graph'
urlpatterns = [
    path('', views.index, name='index'),
    path('charts/simple.png', views.simple, name='charts'),
]

hello/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from hello import views

app_name = 'hello'
urlpatterns = [
    path('', views.HelloListView.as_view(), name = 'index'),
    path('pdf/', views.HelloPdfListView.as_view(), name = 'pdf'),
    path('pdf2/', views.HelloPdf, name = 'pdf2'),
    path('pdf3/', views.HelloPdf2, name = 'pdf3'),
    path('detail/<int:pk>', views.HelloDetailView.as_view(), name = 'detail'),
    path('create/', views.HelloCreateView.as_view(), name = 'create'),
    path('update/<int:pk>', views.HelloUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>', views.HelloDeleteView.as_view(), name = 'delete'),
#    path('check', views.check, name = 'check'),
    path('message', views.MessageListView.as_view(), name = 'message'),
#    path('message/create', views.MessageCreateView.as_view(), name = 'message:create'),
#    path('message/detail/<int:pk>', views.MessageDetailView.as_view(), name = 'message:detail'),
]

mail/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'mail'
urlpatterns = [
    path('', views.index, name='index'),
]

message/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from message.views.message_list_view import MessageListView

app_name = 'message'
urlpatterns = [
    path('', MessageListView.as_view(), name = 'index'),
]

sns/urls.py
from django.urls import path
from .views import index, groups, add, creategroup, post, share, good

app_name = 'sns'
urlpatterns = [
    path('', index.index, name='index'),
    path('groups', groups.groups, name='groups'),
    path('add', add.add, name='add'),
    path('creategroup', creategroup.creategroup, name='creategroup'),
    path('post', post.post, name='post'),
    path('share/<int:share_id>', share.share, name='share'),
    path('good/<int:good_id>', good.good, name='good'),
]

message/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Messageモデル
class Message(models.Model):

    # 外部キーの設定
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # テーブルの項目を定義
    content = models.TextField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + '(' + str(self.owner) + ')'

    class Meta:
        ordering = ('-pub_date',)

sns/models/message.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Messageモデル
class Message(models.Model):

    # 外部キーの設定
    owner = models.ForeignKey(User, on_delete=models.CASCADE, \
                              related_name='message_owner')
    group = models.ForeignKey('Group', on_delete=models.CASCADE)

    # テーブルの項目を定義
    content = models.TextField(max_length=1000)
    share_id = models.IntegerField(default=-1)
    good_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + '(' + str(self.owner) + ')'

    def get_share(self):
        return Message.objects.get(id=self.share_id)

    class Meta:
        ordering = ('-pub_date',)

message/views/message_list_view.py
# -*- coding: utf-8 -*-

from django.views.generic import ListView

from message.models import Message

# Create your views here.
class MessageListView(ListView):
    model = Message
    template_name = 'message/index.html'
    paginate_by = 4

sns/views/common.py
from django.contrib.auth.models import User

from ..models import Message, Friend, Group

from django.db.models import Q

class Common:
    # 指定されたグループおよび検索文字によるMessageの取得
    @staticmethod
    def get_your_group_message(owner, glist, find):
        # publicの取得
        (public_user, public_group) = Common.get_public()

        # チェックされたGroupの取得
        groups = Group.objects.filter(Q(owner=owner) \
                |Q(owner=public_user)).filter(title__in=glist)

        # Groupに含まれるFriendの取得
        me_friends = Friend.objects.filter(group__in=groups)

        # FriendのUserをリストにまとめる
        me_users = []
        for f in me_friends:
            me_users.append(f.user)

        # UserリストのUserが作ったGroupの取得
        his_groups = Group.objects.filter(owner__in=me_users)
        his_friends = Friend.objects.filter(user=owner) \
                .filter(group__in=his_groups)
        me_groups = []
        for hf in his_friends:
            me_groups.append(hf.group)

        # groupがgroupsに含まれるか、me_groupsに含まれるMessageの取得
        if find==None:
            messages = Message.objects.filter(Q(group__in=groups) \
                |Q(group__in=me_groups))[:100]
        else:
            messages = Message.objects.filter(Q(group__in=groups) \
                |Q(group__in=me_groups)) \
                .filter(content__contains=find)[:100]
        return messages
    
    # publicなUserとGroupを取得する
    @staticmethod
    def get_public():
        public_user = User.objects.filter(username='public').first()
        public_group = Group.objects.filter \
                (owner=public_user).first()
        return (public_user, public_group)

common/templates/includes/footer.html
<footer class="bg-faded ">
    <div class="max_height child-footer">
        Copyright &copy;2019 <a href="http://www.groover.co.jp/" target="_blank">Groover Co.,Ltd.</a> All Right Reserved.
    </div>
</footer>

common/templates/includes/header.html
<header>
    <nav class="bg-faded max_height">
        <a class="max_height child-header header-font" href="/">xxx システム</a>
    </nav>
</header>

common/templates/includes/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        {% if message.tags %}
            <!-- errorだけbootstrapのclass名と合わないためコンバート -->
            {% if message.tags == 'error' %}
                <div
                    style="margin-left: -40px"
                    class="alert alert-danger alert-dismissible fade show"
                    role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  {{ message }}
                </div>
            {% else %}
                <div
                    style="margin-left: -40px"
                    class="alert alert-{{ message.tags }} alert-dismissible fade show"
                    role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  {{ message }}
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
</ul>
{% endif %}

common/templates/includes/side_menu.html
<nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
  <ul class="nav nav-pills flex-column">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hello:index' %}">ユーザー管理</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'sns:index' %}" style="pointer-events: none;">sns</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'mail:index' %}" style="pointer-events: none;">mail</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'message:index' %}">message</a>
    </li>
<!--
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hello:pdf' %}">pdf(xhtml2pdf)</a>
    </li>
-->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hello:pdf2' %}">pdf(reportLab)</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'hello:pdf3' %}">pdf(excel)</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'graph:index' %}">graph(matplotlab)</a>
    </li>
  </ul>
</nav>