config/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/index.html'), name="home"),
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('mail/', include('mail.urls')),
    path('message/', include('message.urls')),
    path('sns/', include('sns.urls')),
    path('upload_form/', include('upload_form.urls')),
    path('graph/', include('graph.urls')),
]

hello/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from hello import views

app_name = 'hello'
urlpatterns = [
    path('', views.HelloListView.as_view(), name = 'index'),
    path('pdf/', views.HelloPdfListView.as_view(), name = 'pdf'),
    path('pdf2/', views.HelloPdf, name = 'pdf2'),
    path('pdf3/', views.HelloPdf2, name = 'pdf3'),
    path('detail/<int:pk>', views.HelloDetailView.as_view(), name = 'detail'),
    path('create/', views.HelloCreateView.as_view(), name = 'create'),
    path('update/<int:pk>', views.HelloUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>', views.HelloDeleteView.as_view(), name = 'delete'),
#    path('check', views.check, name = 'check'),
    path('message', views.MessageListView.as_view(), name = 'message'),
#    path('message/create', views.MessageCreateView.as_view(), name = 'message:create'),
#    path('message/detail/<int:pk>', views.MessageDetailView.as_view(), name = 'message:detail'),
]

message/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from message.views.message_list_view import MessageListView

app_name = 'message'
urlpatterns = [
    path('', MessageListView.as_view(), name = 'index'),
]

sns/urls.py
from django.urls import path
from .views import index, groups, add, creategroup, post, share, good

app_name = 'sns'
urlpatterns = [
    path('', index.index, name='index'),
    path('groups', groups.groups, name='groups'),
    path('add', add.add, name='add'),
    path('creategroup', creategroup.creategroup, name='creategroup'),
    path('post', post.post, name='post'),
    path('share/<int:share_id>', share.share, name='share'),
    path('good/<int:good_id>', good.good, name='good'),
]

hello/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, ValidationError

# Create your models here.
def number_only(value):
    if (re.match(r'^[0-9]*$', value) == None):
        raise ValidationError(
                '%(value)s is not Number!', \
                params = { 'value' : value },
                )

class Friend(models.Model):
    name = models.CharField(max_length=100)
    mail = models.EmailField(max_length=200)
    gender = models.BooleanField()
    age = models.IntegerField(validators=[ \
          MinValueValidator(0), \
          MaxValueValidator(150)])
    birthday = models.DateField()

    def __str__(self):
        return '<Friend:id=' + str(self.id) + ', ' + \
            self.name + '(' + str(self.age) + ')>'

class Message(models.Model):
    friend = models.ForeignKey(Friend, on_delete = models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<Message:id=' + str(self.id) + ', ' + \
                self.title + '(' + str(self.pub_date) + ')>'

    class Meta:
        ordering = ('pub_date', )

message/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Messageモデル
class Message(models.Model):

    # 外部キーの設定
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # テーブルの項目を定義
    content = models.TextField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + '(' + str(self.owner) + ')'

    class Meta:
        ordering = ('-pub_date',)

sns/models/message.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User

# Messageモデル
class Message(models.Model):

    # 外部キーの設定
    owner = models.ForeignKey(User, on_delete=models.CASCADE, \
                              related_name='message_owner')
    group = models.ForeignKey('Group', on_delete=models.CASCADE)

    # テーブルの項目を定義
    content = models.TextField(max_length=1000)
    share_id = models.IntegerField(default=-1)
    good_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + '(' + str(self.owner) + ')'

    def get_share(self):
        return Message.objects.get(id=self.share_id)

    class Meta:
        ordering = ('-pub_date',)

hello/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Friend, Message

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name', 'mail', 'gender', 'age', 'birthday']

    def __init__(self, *args, **kwargs):
        super(FriendForm, self).__init__(*args, **kwargs)
        print(self.fields)

        # bootstrap用の定義
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class FindForm(forms.Form):
    find = forms.CharField(label = 'find', required = False)

class CheckForm(forms.Form):
    str = forms.CharField(label = 'String')

    # バリデーションエラー発生時にエラーメッセージを指定
#    def clean(self):
#        cleaned_data = super().clean()
#        str = cleaned_data['str']
#        if (str.lower().startswith('no')):
#            raise forms.ValidationError('You input "NO"!')

    # 文字列のバリデーション
    # empty = forms.CharField(label = 'Empty', empty_value = True)
    # min_length = forms.CharField(label = 'Min', min_length = 10)
    # max_length = forms.CharField(label = 'Max', max_length = 10)

    # 数値のバリデーション
    # required = forms.IntegerField(label = 'Required')
    # min_value = forms.IntegerField(label = 'Min', min_value = 100)
    # max_value = forms.IntegerField(label = 'Max', max_value = 1000)

    # 日付のバリデーション
    # date = forms.DateField(label = 'Date', input_formats=['%d'])
    # time = forms.TimeField(label = 'Time')
    # datetime = forms.DateTimeField(label = 'DateTime')

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title', 'content', 'friend']

hello/views.py
# -*- coding: utf-8 -*-
import io
import os

from django.conf import settings

from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.loader import get_template

from django.contrib import messages

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from xhtml2pdf import pisa

from .models import Friend, Message
from .forms import FriendForm, MessageForm

from common.utils.pdf.excel_to_pdf import ExcelToPdf
from hello.utils.pdf.sample_render import SampleRender

# Pythonでディレクトリの上層にあるモジュールをimportするときの注意点
# http://d.hatena.ne.jp/chlere/20110618/1308369842

# ユーザ一覧
class HelloListView(ListView):
    model = Friend
    template_name = 'hello/index.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "ユーザー一覧画面"
        return context

#    def get_queryset(self):
#        object_list = self.model.objects.all().order_by('id')
#        q_friend= self.request.GET.get('friend')
#        if q_friend is not None:
#            if q_friend != "":
#                object_list = object_list.filter(friend=q_friend)
#        return object_list

# ユーザ登録
class HelloCreateView(CreateView):
    model = Friend
    form_class = FriendForm
    template_name = "hello/create.html"
    success_url = "/hello"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "ユーザー登録画面"
        return context

# ユーザ詳細
class HelloDetailView(DetailView):
    model = Friend
    form_class = FriendForm
    template_name = "hello/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "ユーザー詳細画面"
        return context

# ユーザ編集
class HelloUpdateView(UpdateView):
    model = Friend
    form_class = FriendForm
    template_name = 'hello/update.html'
    success_url = "/hello"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "ユーザー編集画面"
        return context

# ユーザ削除
class HelloDeleteView(DeleteView):
    model = Friend
    form_class = FriendForm
    template_name = 'hello/delete.html'
    success_url = "/hello"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "ユーザー削除画面"
        return context

#　メッセージ一覧
class MessageListView(ListView):
    model = Message
    template_name = 'hello/message.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "メッセージ一覧画面"
        return context

# メッセージ登録
class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'hello/message.html'
    success_url = "/hello"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "メッセージ登録画面"
        return context

# メッセージ詳細
class MessageDetailView(DetailView):
    model = Message
    form_class = MessageForm
    template_name = 'hello/message.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "メッセージ詳細画面"
        return context

class HelloPdfListView(ListView):
    model = Friend
    template_name = 'hello/index.html'

    def render_to_response(self, context):
        html = get_template(self.template_name).render(self.get_context_data())
        result = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode('utf-8')),
            result,
            link_callback=link_callback,
            encoding='utf-8',
        )

        if not pdf.err:
            return HttpResponse(
                result.getvalue(),
                content_type='application/pdf'
            )

        return HttpResponse('<pre>%s</pre>' % escape(html))

def link_callback(uri, rel):
    path = os.path.join(settings.BASE_DIR, 'common', 'static/pdf')

    if not os.path.isfile(path):
        raise Exception(path)

    return path

def HelloPdf(request):
    # pdf 出力
    SampleRender().render()

    messages.success(request, 'PDF(reportLab)の出力に成功しました')

    # 画面遷移したくないので強制的に印刷ボタンがあるページに戻る
    return redirect("hello:index")

def HelloPdf2(request):
    # pdf 出力
    ExcelToPdf.export()

    messages.success(request, 'PDF(excel)の出力に成功しました')

    # 画面遷移したくないので強制的に印刷ボタンがあるページに戻る
    return redirect("hello:index")

message/views/message_list_view.py
# -*- coding: utf-8 -*-

from django.views.generic import ListView

from message.models import Message

# Create your views here.
class MessageListView(ListView):
    model = Message
    template_name = 'message/index.html'
    paginate_by = 4

hello/templates/hello/check.html
{% extends "layout.html" %}
{% block content %}
<h1>{{title}}</h1>
<p>{{message}}</p>
<hr>
<ol>
    {% for item in form %}
        <li>{{ item.name }} ({{ item.value }})
            :{{ item.errors.as_text }}</li>
    {% endfor %}
</ol>
<table>
    <form action="{% url 'hello:check' %}" method="post">
        {% csrf_token %}
        <tr><th>名前</th><td>{{ form.name }}</td></tr>
        <tr><th>メール</th><td>{{ form.mail }}</td></tr>
        <tr><th>性別</th><td>{{ form.gender }}</td></tr>
        <tr><th>年齢</th><td>{{ form.age }}</td></tr>
        <tr><th>誕生日</th><td>{{ form.birthday }}</td></tr>
        <tr>
            <td></td>
            <td><input type="submit" value="click"></td>
        </tr>
    </form>
</table>
{% endblock %}

hello/templates/hello/create.html
{% extends "layout.html" %}
{% block title %}
ユーザー作成
{% endblock %}

{% block page_title %}
ユーザー作成
{% endblock %}

{% block content %}
<p>ユーザー情報を入力してください。</p>
<form action="{% url 'hello:create' %}" method="post">
    <table class="table">
        {% csrf_token %}
        {{ form.as_table }}
    </table>

    <button type="submit" class="btn btn-primary">登録</button>

    <input
        type="button"
        class="btn btn-primary"
        onclick="location.href='/hello'"
        value="戻る">
</form>
{% endblock %}

hello/templates/hello/delete.html
{% extends "layout.html" %}
{% block title %}
ユーザー削除
{% endblock %}

{% block page_title %}
ユーザー削除
{% endblock %}

{% block content %}
<p>※以下のレコードを削除します。</p>
<form action="{% url 'hello:delete' friend.id %}" method="post">
    {% csrf_token %}
    <table class="table">
        <tr><th>ID</th><td>{{friend.id}}</td></tr>
        <tr><th>Name</th><td>{{friend.name}}</td></tr>
        <tr><th>Gender</th>
        <td>
            {% if friend.gender == False %}male{% endif %}
            {% if friend.gender == True %}female{% endif %}
        </td></tr>
        <tr><th>Email</th><td>{{friend.mail}}</td></tr>
        <tr><th>Age</th><td>{{friend.age}}</td></tr>
        <tr><th>Birth</th><td>{{friend.birthday}}</td></tr>
        </tr>
    </table>
    <button type="submit" class="btn btn-danger del_confirm">削除</button>

    <input
        type="button"
        class="btn btn-primary"
        onclick="location.href='/hello'"
        value="戻る">
</form>

{% endblock %}

hello/templates/hello/detail.html
{% extends "layout.html" %}
{% block title %}
ユーザー詳細
{% endblock %}

{% block page_title %}
ユーザー詳細
{% endblock %}

{% block content %}
<table class="table">
    <tr><th>ID</th><td>{{friend.id}}</td></tr>
    <tr><th>Name</th><td>{{friend.name}}</td></tr>
    <tr><th>Gender</th>
    <td>
        {% if friend.gender == False %}male{% endif %}
        {% if friend.gender == True %}female{% endif %}
    </td></tr>
    <tr><th>Email</th><td>{{friend.mail}}</td></tr>
    <tr><th>Age</th><td>{{friend.age}}</td></tr>
    <tr><th>Birth</th><td>{{friend.birthday}}</td></tr>
    </tr>
</table>

<input
    type="button"
    class="btn btn-primary"
    onclick="location.href='/hello'"
    value="戻る">
{% endblock %}

hello/templates/hello/find.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{{title}}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    </head>
    <body>
        <h1>{{title}}</h1>
        <p>{{message|safe}}</p>
        <table>
            <form action="{% url 'hello:find' %}" method="post">
                {% csrf_token %}
                {{form}}
                <tr>
                    <td></td>
                    <td><input type="submit" value="click"></td>
                </tr>
            </form>
        </table>
        <table>
            <tr>
                <th>data</th>
                <th></th>
                <th></th>
            </tr>
            {% for item in data %}
            <tr>
                <td>{{item}}</td>
                <td><a href="{% url 'hello:edit' item.id %}">Edit</a></td>
                <td><a href="{% url 'hello:delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

hello/templates/hello/index.html
{% extends "layout.html" %}
{% block title %}
ユーザー一覧
{% endblock %}

{% block page_title %}
ユーザー一覧
{% endblock %}


{% block content %}
<!-- 登録ボタン -->
<div style="padding:3px;">
    <input
        class="btn btn-primary"
        onclick="location.href='{% url 'hello:create' %}'"
        value="新規登録">

    <input
        class="btn btn-primary"
        onclick="location.href='{% url 'hello:pdf3' %}'"
        value="pdf印刷">
</div>

<!-- 検索フォーム -->
<!--
    検索の参考ページ
    https://takaxtech.com/2018/09/23/article260/
-->

<!-- ページネーション -->
{% include 'includes/pagination.html' %}

<!-- 削除確認ダイアログ -->
{% include 'includes/delete_dialog.html' %}

<!-- 表 -->
<table class="table table-condensed table-bordered table-hover">
    <thead class="thead-light">
        <tr class="active">
            <th>id</th>
            <th>名前</th>
            <th>年齢</th>
            <th>メールアドレス</th>
            <th>誕生日</th>
            <th>メッセージ</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </tdead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td><a href="{% url 'hello:detail' item.pk %}">{{item.id}}</a></td>
            <td>{{item.name}}</td>
            <td>{{item.age}}</td>
            <td>{{item.mail}}</td>
            <td>{{item.birthday}}</td>
            <td>
                <ul>
                    {% for ob in item.message_set.all %}
                        <li>{{ob.title}}</li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <input
                    type="button"
                    class="btn btn-primary btn-sm"
                    onclick="location.href='{% url 'hello:update' item.pk %}'"
                    value="編集">
            </td>
            <td>
                <input
                    type="button"
                    class="btn btn-danger del_confirm btn-sm"
                    onclick="location.href='{% url 'hello:delete' item.pk %}'"
                    value="削除">
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

hello/templates/hello/message.html
{% extends "layout.html" %}
{% block content %}
<input
    class="btn btn-primary"
    onclick="location.href='{% url 'hello:message:create' %}'"
    value="新規登録">

<!-- ページネーション -->
{% include 'includes/pagination.html' %}

<!-- 表 -->
<table class="table table-condensed table-bordered table-hover">
    <thead class="thead-light">
        <tr class="active">
            <th>title</th>
            <th>name</th>
            <th>datetme</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{item.title}}</td>
                <td>{{item.friend.name}}</td>
                <td>{{item.pub_date}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

hello/templates/hello/update.html
{% extends "layout.html" %}
{% block title %}
ユーザー編集
{% endblock %}

{% block page_title %}
ユーザー編集
{% endblock %}

{% block content %}
<p>ユーザー情報を変更してください。</p>
<form action="{% url 'hello:update' friend.id %}" method="post">
    <div class="form-group">
        <table class="table">
            {% csrf_token %}
            {{ form.as_table }}
        </table>
    </div>
    <button type="submit" class="btn btn-primary">更新</button>

    <input
        type="button"
        class="btn btn-primary"
        onclick="location.href='/hello'"
        value="戻る">
</form>
{% endblock %}